[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm -F
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autorestart=true

[program:catalog-worker]
command=php /app/scripts/catalog-worker.php
user=www-data
autorestart=true
stopwaitsecs=10
